Feature/task 119 progressbar
DTS-STN/ExperimentalBenefitsFinderFrontEnd pull request #26
Opened 2020-10-28 03:27 UTC by MarcoGoC

# ProgressBar 

shows a progressbar with the percentage 

## Taiga Link 🔗
https://taiga.dts-stn.com/project/pond-dts-experimental-benefit-finder/task/119?kanban-status=117

## Checklist ✅
- [x] created story for all visual components
- [x] created or modified necessary unit tests
- [ ] created or modified e2e tests
- [ ] modified README or any applicable documentation on the changes you made

2020-10-28 13:38 UTC, MarcoGoC commented
Added bold to label of the Combo control and round corners to the select
as you know select looks different depending on the OS and browser

2020-10-28 15:24 UTC, Moro-Code requested changes
This is what I see so far. As per the convention we are using could you please take out the extra directory you placed your components in. All assets should be in an assets folder that you can create on the top level of the src directory in an images sub folder.

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/ProgressBar/ProgressBar.js
> + * progressBar () component
should be a little bit more descriptive

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/ProgressBar/ProgressBar.js
> +export function ProgressBar(props) {
Black bar in mobile view. It might be easier to use svg's or even just divs with 100% border radius

![mobile-progress-bar-error](https://user-images.githubusercontent.com/26819992/97449459-10f73000-1908-11eb-8912-d9532a0e6d75.png)

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Alink/Alink.js
> +    <a
This should use react router Link component https://reactrouter.com/web/guides/quick-start

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Alink/Alink.stories.js
> +export const Example2 = Template.bind({});
should be explicit in what these states show i.e. (LinkWithStyling)

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +          {required ? (
minor nitpick but you don't need circle brackets here

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +  lblText: PropTypes.string.isRequired,
minor nitpick: no need to shorten here labelText is much clearer

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +  customSelClass: PropTypes.string,
no need to shorten, makes props less clear

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +          data-cy={id + "-label"}
data-cy should be a role rather than an id as mentioned in the cypress docs. should be something such as `data-cy="question"` and `data-cy="label"` but this is a minor nitpick you can leave this as is if you are inclined

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.stories.js
> +export const Example1 = Template.bind({});
State naming should be explicit

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.test.js
> +it("renders Example1 ", () => {
you should test if the options render properly with the text you expect and the label has the text you expect. you should not getElementById here. This is bad practice, you should be able to get the elements you need based on role. Similar to cypress

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/ProgressBar/ProgressBar.stories.js
> +export const Example1 = Template.bind({});
explicit naming

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +import React from "react";
Needs to be mobile friendly 
![Screen Shot 2020-10-28 at 11 02 17 AM](https://user-images.githubusercontent.com/26819992/97454379-1440ea80-190d-11eb-87ca-5d85347af465.png)

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +          rounded={false}
no need to explicitly pass rounded as false

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +          Back
Back text ect should be passed in for i18n

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +          Skip
should be passed in

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +    props.nextClick(props.benefitId);
`prop.benefitId` doesn't exist

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.js
> +PrevNextBar.propTypes = {
Please define callbacks in props

2020-10-28 15:24 UTC, Moro-Code commented on src/components/molecules/PrevNextBar/PrevNextBar.stories.js
> +Example1.args = {
Call this Primary for primary state

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/ActionButton.js
> +  id: PropTypes.string,
this is confusing, there could be a case for setting an id for the button. rename this prop to dataCy

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +          onChange={onChange}
you should pass in the selected option rather than the actual event. Parent components should not be aware of the implementation

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +import React from "react";
Seems like a molecule to me rather than an atom

2020-10-28 15:24 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +        <label
would probably split this into another component so that it can be reused and its cleaner

2020-10-28 15:51 UTC, Moro-Code commented on src/components/atoms/Combo/Combo.js
> +import React from "react";
you did not define the prop for options correctly.
getting the following warning in console

```
 console.error node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: Invalid prop `options` of type `array` supplied to `Combo`, expected `object`.
          in Combo (at Combo.stories.js:9)
          in bound Template (at Combo.test.js:8)
```

2020-11-02 18:52 UTC, MarcoGoC commented on src/components/atoms/ProgressBar/ProgressBar.js
> +export function ProgressBar(props) {
this is going back to the cute triangle because on mobile there is only 3 circles

2020-11-02 18:58 UTC, MarcoGoC commented on src/components/atoms/Alink/Alink.js
> +    <a
not meant for In App navigation but I will change to use link on the other component

2020-11-03 14:22 UTC, MarcoGoC commented on src/components/atoms/Combo/Combo.js
> +          data-cy={id + "-label"}
that was an error I meant -select

2020-11-24 14:18 UTC, Moro-Code approved these changes
made some minor changes. Well done

2020-11-24 14:33 UTC, merged